[2025-03-01 00:17:07] [ERROR] Błąd podczas łączenia z bazą danych: bad auth : authentication failed
